// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj87A4EVB3ScVu_Z_vcV7o8gMY7vSzeEI',
    appId: '1:400825018532:web:2fbb3c8d88ee16f1b95e31',
    messagingSenderId: '400825018532',
    projectId: 'zeoxbits',
    authDomain: 'zeoxbits.firebaseapp.com',
    storageBucket: 'zeoxbits.firebasestorage.app',
    measurementId: 'G-DMFE7XQ6E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD8mA_0rinyEED8NyCbXSe1jYuhEnoyps',
    appId: '1:400825018532:android:207ae5981d85027ab95e31',
    messagingSenderId: '400825018532',
    projectId: 'zeoxbits',
    storageBucket: 'zeoxbits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClD3q0dHyZes9c0fooIp0tBoKMnLaAW7Q',
    appId: '1:400825018532:ios:d25409102bef55b4b95e31',
    messagingSenderId: '400825018532',
    projectId: 'zeoxbits',
    storageBucket: 'zeoxbits.firebasestorage.app',
    iosBundleId: 'com.example.check',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClD3q0dHyZes9c0fooIp0tBoKMnLaAW7Q',
    appId: '1:400825018532:ios:d25409102bef55b4b95e31',
    messagingSenderId: '400825018532',
    projectId: 'zeoxbits',
    storageBucket: 'zeoxbits.firebasestorage.app',
    iosBundleId: 'com.example.check',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj87A4EVB3ScVu_Z_vcV7o8gMY7vSzeEI',
    appId: '1:400825018532:web:f1958cae5db96d70b95e31',
    messagingSenderId: '400825018532',
    projectId: 'zeoxbits',
    authDomain: 'zeoxbits.firebaseapp.com',
    storageBucket: 'zeoxbits.firebasestorage.app',
    measurementId: 'G-Z2Z6BTJYFG',
  );

}